replicaCount: 3

image:
  repository: nginxdemos/hello
  tag: plain-text

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

service:
  port: 80

ingress:
  enabled: false
  host: web-app.homelab.local
