apiVersion: v1
kind: Pod
metadata:
  name: over-quota
  namespace: dev
spec:
  containers:
    - name: app
      image: nginx:1.27-alpine
      resources:
        requests:
          cpu: "800m"
          memory: "256Mi"
        limits:
          cpu: "800m"
          memory: "256Mi"
